---
- name: Repair the jenkins server
  hosts: local 
  tasks:   
  
    - name: load the variables
      include_vars:
        dir: vars
        extensions: [yml]  
            
    - include_role:
        name: jenkins-repair    
      vars:
        project: "{{ product.name }}-cicd" 
        
