apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: pipeline
    name: setup-pipeline
  name: setup-pipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: "https://github.com/Estafet-LTD/estafet-microservices-scrum"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: ansible/setup-pipeline.groovy
    type: JenkinsPipeline
status:
  lastVersion: 0