---

- name: Read the broker pod list
  shell: "oc get pods --selector application=broker -o json"
  register: list_of_broker_pods

- name: Get the name of the Broker Pod
  set_fact: broker_pod="{{list_of_broker_pods.stdout|from_json|json_query('items[0].metadata.name')}}"

- set_fact: broker_pod_vars="{{list_of_broker_pods.stdout|from_json|json_query('items[0].spec.containers[0].env')}}"
- set_fact: broker_query_user="[?name=='AMQ_USER'].value"
- set_fact: broker_query_password="[?name=='AMQ_PASSWORD'].value"

- name: Get the user name for the Broker Pod
  set_fact: broker_pod_user="{{broker_pod_vars|json_query(broker_query_user)}}"

- set_fact: broker_pod_user={{broker_pod_user|replace("[u", "")|replace("]", "")}}

- name: Get the password for the Broker Pod
  set_fact: broker_pod_password="{{broker_pod_vars|json_query(broker_query_password)}}"

- set_fact: broker_pod_password={{broker_pod_password|replace("[u", "")|replace("]", "")}}

- name: Read the broker pod services
  shell: "oc get service/broker-amq-tcp -o json"
  register: list_of_broker_services

- name: Get the cluster id address for the broker
  set_fact: broker_ip="{{list_of_broker_services.stdout|from_json|json_query('spec.clusterIP')}}"
