---
# Define the name and description of the OpenShift project
- set_fact: project="test"
- set_fact: project_description="Test Environment for Microservices Scrum"
- set_fact: expose_basic_ui=true
- set_fact: external_db=true
    
- include: environment-setup.yml
- include: jaeger-setup.yml
- include: create-db.yml

- name: Allows jenkins to access the test environment
  shell: "oc policy add-role-to-user edit system:serviceaccount:cicd:jenkins -n test"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - jenkins   

