---
- debug:
    msg: Executing microservices setup for {{ project }} . projects are ...

- debug:
    msg: Environment {{ project }} projects are {{ microservices_scrum_projects }} ...

- name: Define Openshift project
  shell: "oc project {{ project }}"
  tags:
    - openshift

- include: amq-vars.yml
- include: create-db.yml

- name: Create the db based microservices applications using the source to image builder
  include_tasks: "create-app-with-db.yml"
  vars:
    repo: "{{ item.repo }}"
    microservice: "{{ item.name }}"
  when: item.db
  with_items: "{{ microservices_scrum_projects }}"
  tags:
    - openshift

- name: Create the non db based microservices applications using the source to image builder
  include_tasks: "create-app-without-db.yml"
  vars:
    repo: "{{ item.repo }}"
    microservice: "{{ item.name }}"
  when: not item.db
  with_items: "{{ microservices_scrum_projects }}"
  tags:
    - openshift

- debug:
    msg: Executed microservices setup for {{ project }}.
