---
- debug:
    msg: "Get the source code for {{ repo }}. Test environment is {{ test_environment }}."

- set_fact: branch="master"

- name: Set expose_service if test_environment is true
  set_fact: expose_service=true
  when: test_environment

- name: Fetch the latest Git tag for the {{ repo }} repo
  shell: "git describe --abbrev=0 --tags"
  args:
    chdir: "{{ workdir }}/{{ repo }}"
  when: test_environment
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - git

- set_fact: branch="{{ command_result.stdout }}"
  when: test_environment

- debug:
    msg: "pre-create-app for {{ repo }} in {{ project }}. OK."