apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: pipeline
    name: deploy-prod
  name: deploy-prod
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: "https://github.com/stericbro/estafet-microservices-scrum"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: ansible/prod-pipeline.groovy
    type: JenkinsPipeline
status:
  lastVersion: 0